name: Deploy Chess Game

on:
  push:
    branches:
      - main  # Set the branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history (necessary if you want to retain commit history)

      # Step 2: Install dependencies (if any, like npm for JavaScript projects)
      - name: Install dependencies
          # Only necessary if you have a `package.json` with dependencies

      # Step 3: Build the project (if necessary)
      - name: Build the project
          # You can remove this if you don't need any build steps

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Use the directory containing your static files (e.g., `public`, `dist`, etc.)

      # Step 5: Verify deployment files (optional)
      - name: Verify index.html
        run: ls -la ./public  # Check if `index.html` exists in the `public` folder
